version: '3'

services:
  knomp:
    container_name: knomp
    network_mode: host
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./config.json:/home/knomp/knomp/config.json
      - ./coins:/home/knomp/knomp/coins
      - ./libs:/home/knomp/knomp/libs
      - ./pool_configs:/home/knomp/knomp/pool_configs
      - ./website:/home/knomp/knomp/website
    # ports:
    #   - 8080:8080
    #   - 3333:3333
    depends_on:
      - redis

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
      - REDIS_PASSWORD=<change this>
      - HTTP_USER=<change this>
      - HTTP_PASSWORD=<change this>
    ports:
      - 8081:8081
    depends_on:
      - redis

  redis:
    image: redis:6.0.10-alpine
    container_name: redis
    network_mode: host
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./redis-data:/data
    # ports:
    #   - 6379:6379
    restart: always
